In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
%matplotlib inline

In [2]:
!wget -O FuelConsumption.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/FuelConsumptionCo2.csv

--2020-01-15 12:28:49--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/FuelConsumptionCo2.csv
Resolving s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 67.228.254.196
Connecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72629 (71K) [text/csv]
Saving to: ‘FuelConsumption.csv’

FuelConsumption.csv 100%[===================>]  70.93K  96.7KB/s    in 0.7s    

2020-01-15 12:28:51 (96.7 KB/s) - ‘FuelConsumption.csv’ saved [72629/72629]



In [3]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [6]:
from sklearn.model_selection import train_test_split
df = pd.read_csv("FuelConsumption.csv")

In [7]:
X = df[["ENGINESIZE"]]
y = df["CO2EMISSIONS"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [8]:
poly = PolynomialFeatures(degree=2)
train_x_poly = poly.fit_transform(X_train)
print(train_x_poly)

[[ 1.    3.5  12.25]
 [ 1.    2.    4.  ]
 [ 1.    1.8   3.24]
 ...
 [ 1.    3.7  13.69]
 [ 1.    5.   25.  ]
 [ 1.    3.7  13.69]]


In [9]:
clf = LinearRegression()
train_y_ = clf.fit(train_x_poly, y_train)
# The coefficients
print ('Coefficients: ', clf.coef_)
print ('Intercept: ',clf.intercept_)

Coefficients:  [ 0.         49.23159361 -1.30674654]
Intercept:  110.42668525795517


In [14]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
test_x_poly = poly.fit_transform(X_test)
test_y_ = clf.predict(test_x_poly)

In [17]:
#test_y_

In [16]:
mean_absolute_error(y_test, test_y_)

25.595135472294505